// Runtime view of what's actually on disk under public/audio and public/images.
// Generated by scripts/build-asset-index.mjs at build time.

import assetIndex from '../data/assets.generated.json';

const audioSet = new Set<string>(assetIndex.audio);
const imageSet = new Set<string>(assetIndex.images);

export function hasAudio(path: string): boolean {
  return audioSet.has(path);
}

export function hasImage(path: string): boolean {
  return imageSet.has(path);
}

export function audioCount(): number {
  return audioSet.size;
}

export function imageCount(): number {
  return imageSet.size;
}
